version: '3'
services:

  kafka-first:
    image: docker-kafka
    stdin_open: true
    tty: true
    environment:
      - KFK_NODE_ID=1
      - KFK_QUORUM_VOTERS=${KFK_QUORUM_VOTERS}
      - KFK_ADV_LISTENERS=kafka-first
      - KFK_LOG_DIRS=${KFK_LOG_DIRS}
      - KFK_CLUSTER_ID=${KFK_CLUSTER_ID}

    volumes:
      - ./data/kafka-first:${KFK_LOG_DIRS}
    ports:
      - "9001:9092"
    networks:
      - kafka-net
    command: bash /app/kafka_2.13-3.5.0/setup.sh
      
  kafka-second:
    image: docker-kafka
    stdin_open: true
    tty: true
    environment:
      - KFK_NODE_ID=2
      - KFK_QUORUM_VOTERS=${KFK_QUORUM_VOTERS}
      - KFK_ADV_LISTENERS=kafka-second
      - KFK_LOG_DIRS=${KFK_LOG_DIRS}
      - KFK_CLUSTER_ID=${KFK_CLUSTER_ID}
    volumes:
      - ./data/kafka-second:${KFK_LOG_DIRS}
    ports:
      - "9002:9092"
    networks:
      - kafka-net
    command: bash /app/kafka_2.13-3.5.0/setup.sh

  kafka-third:
    image: docker-kafka
    stdin_open: true
    tty: true
    environment:
      - KFK_NODE_ID=3
      - KFK_QUORUM_VOTERS=${KFK_QUORUM_VOTERS}
      - KFK_ADV_LISTENERS=kafka-third
      - KFK_LOG_DIRS=${KFK_LOG_DIRS}
      - KFK_CLUSTER_ID=${KFK_CLUSTER_ID}
    volumes:
      - ./data/kafka-third:${KFK_LOG_DIRS}
    ports:
      - "9003:9092"
    networks:
      - kafka-net
    command: bash /app/kafka_2.13-3.5.0/setup.sh

networks:
  kafka-net:
    driver: bridge
